[package]
name = "rotter"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
toml = { version = "=1.1.6", default-features = false, features = ["std", "parse", "serde"] }
tree-sitter = "=0.27.0"
tree-sitter-bash = "=0.25.1"
tree-sitter-go = "=0.25.0"
tree-sitter-lua = "=0.5.0"
tree-sitter-nix = "=0.3.0"
tree-sitter-rust = "=0.24.2"
tree-sitter-toml-ng = "=0.7.0"
tree-sitter-yaml = "=0.7.2"
